### ISSUE TITLE
Upgrade enterprise-access to Django 4.2

### ISSUE THREAD

**Issue by iamsobanjaved** [openedx/enterprise-access#254]
## Description
Under the effort of https://github.com/openedx/public-engineering/issues/199, complete all of the following steps to complete the upgrade.

```[tasklist]
### Subtasks
- [ ] Update the pinned Django version in the requirements to Django==4.2
- [ ]  Run make upgrade to update all dependencies for Django 4.2.
- [ ]  Update the repo support field in the [IDA Upgrade Sheet](https://openedx.atlassian.net/wiki/spaces/AC/pages/3815637011/Django+4.2+Upgrade+List+of+IDAs).
```
